// Code generated by as3flatc. DO NOT EDIT.
package example
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class PointView extends as3flatbuffers.TableView
    {
        public function bind(input:flash.utils.ByteArray, rootOffset:uint = 0):PointView
        {
            bindRoot(input, rootOffset);
            return this;
        }

        public function get x():Number
        {
            return float32(0, 0);
        }

        public function get y():Number
        {
            return float32(1, 0);
        }

        public function unpack(destination:Point = null):Point
        {
            if (!destination) destination = new Point();
            destination.x = this.x;
            destination.y = this.y;
            return destination;
        }
    }
}
