// Code generated by as3flatc. DO NOT EDIT.
package example
{
    import as3flatbuffers.Pack;
    import as3flatbuffers.Unpack;
    import as3flatbuffers.UnpackContext;
    import avm2.intrinsics.memory.*;
    import flash.utils.ByteArray;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class Point
    {
        private static const PACK:as3flatbuffers.PackContext = new as3flatbuffers.PackContext();
        private static const UNPACK:as3flatbuffers.UnpackContext = new as3flatbuffers.UnpackContext();

        public var x:Number = 0;
        public var y:Number = 0;

        public static function reset(msg:Point):void
        {
            msg.x = 0;
            msg.y = 0;
        }

        public static function clone(source:Point):Point
        {
            if (!source)
                return null;

            const destination:Point = new Point();
            destination.x = source.x;
            destination.y = source.y;

            return destination;
        }

        /** Replace dst with packed bytes. Caller must select little-endian. Returns dst at position zero. */
        public static function pack(source:Point, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.PackContext = PACK;
            try
            {
                as3flatbuffers.Pack.begin(context, dst, true);
                as3flatbuffers.Pack.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Pack.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Point, context:as3flatbuffers.PackContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            as3flatbuffers.Pack.prepare(context, 2);
            as3flatbuffers.Pack.reserveVtable(context, 2);
            as3flatbuffers.Pack.prepare(context, 4);
            as3flatbuffers.Pack.startTable(context);
            if (source.x != 0)
            {
                as3flatbuffers.Pack.addFloat32(context, 0, source.x);
            }
            if (source.y != 0)
            {
                as3flatbuffers.Pack.addFloat32(context, 1, source.y);
            }
            return as3flatbuffers.Pack.endTable(context);
        }

        /** Decode a FlatBuffer whose root-offset word starts at offset. */
        public static function unpack(bytes:flash.utils.ByteArray, destination:Point = null, offset:uint = 0):Point
        {
            const context:as3flatbuffers.UnpackContext = UNPACK;
            const previous:flash.utils.ByteArray = as3flatbuffers.Unpack.begin(context, bytes);
            try
            {
                destination = unpackFrom(context, as3flatbuffers.Unpack.root(context, offset), destination);
            }
            finally
            {
                as3flatbuffers.Unpack.end(context, previous);
            }
            return destination;
        }

        /** Internal generated entry point; context must already own domain memory. */
        public static function unpackFrom(context:as3flatbuffers.UnpackContext, base:uint, destination:Point):Point
        {
            const vtable:uint = as3flatbuffers.Unpack.vtable(context, base);
            const vtableSize:uint = li16(vtable);
            const objectSize:uint = li16(vtable + 2);
            if (!destination)
                destination = new Point();

            const position0:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 4, 4);
            if (!position0)
            {
                destination.x = 0;
            }
            else
            {
                destination.x = lf32(position0);
            }

            const position1:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 6, 4);
            if (!position1)
            {
                destination.y = 0;
            }
            else
            {
                destination.y = lf32(position1);
            }
            return destination;
        }
    }
}
