// Code generated by as3flatc. DO NOT EDIT.
package example
{
    import as3flatbuffers.Builder;

    /** Owned mutable value. pack() returns an offset for Builder.finish(). */
    public final class Point
    {
        public var x:Number = 0;
        public var y:Number = 0;

        public function Point()
        {
        }

        public function reset():void
        {
            this.x = 0;
            this.y = 0;
        }

        public function copyFrom(source:Point):Point
        {
            this.x = source.x;
            this.y = source.y;
            return this;
        }

        public function clone():Point
        {
            return new Point().copyFrom(this);
        }

        public function pack(builder:as3flatbuffers.Builder):uint
        {
            builder.startTable(2);
            builder.addFloat32(0, this.x, 0);
            builder.addFloat32(1, this.y, 0);
            return builder.endTable();
        }
    }
}
