// Code generated by as3flatc. DO NOT EDIT.
package example
{
    import flash.utils.Endian;
    import flash.utils.ByteArray;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class PointView
    {
        private var bytes:flash.utils.ByteArray;
        private var table:uint;
        private var vtable:uint;
        private var vtableSize:uint;
        private var objectSize:uint;

        /** Bind through a root-offset word at rootOffset. */
        public function bind(input:flash.utils.ByteArray, rootOffset:uint = 0):PointView
        {
            bytes = null;
            if (!input) throw new ArgumentError("Input must be non-null");
            if (rootOffset > input.length || input.length - rootOffset < 4)
                throw new RangeError("Truncated root offset");
            input.endian = Endian.LITTLE_ENDIAN;
            input.position = rootOffset;
            const root:uint = input.readUnsignedInt();
            if (root < 4 || root > input.length - rootOffset - 4)
                throw new RangeError("Invalid root offset");
            return bindAt(input, rootOffset + root);
        }

        /** Bind directly to a table's absolute byte position. */
        public function bindAt(input:flash.utils.ByteArray, tablePosition:uint):PointView
        {
            bytes = null;
            if (!input) throw new ArgumentError("Input must be non-null");
            if (tablePosition > input.length || input.length - tablePosition < 4)
                throw new RangeError("Truncated table");
            input.endian = Endian.LITTLE_ENDIAN;
            input.position = tablePosition;
            const vtablePosition:Number = Number(tablePosition) - input.readInt();
            if (vtablePosition < 0 || vtablePosition > input.length - 4)
                throw new RangeError("Invalid vtable offset");
            input.position = uint(vtablePosition);
            const vtSize:uint = input.readUnsignedShort();
            const objSize:uint = input.readUnsignedShort();
            if (vtSize < 4 || (vtSize & 1) || vtSize > input.length - vtablePosition ||
                objSize < 4 || objSize > input.length - tablePosition)
                throw new RangeError("Invalid table size");
            table = tablePosition;
            vtable = uint(vtablePosition);
            vtableSize = vtSize;
            objectSize = objSize;
            bytes = input;
            return this;
        }

        [Inline]
        private final function fieldOffset(slot:uint, width:uint):uint
        {
            if (!bytes) throw new Error("View is not bound");
            if (slot >= vtableSize) return 0;
            bytes.position = vtable + slot;
            const relative:uint = bytes.readUnsignedShort();
            if (!relative) return 0;
            if (relative < 4 || relative > objectSize || width > objectSize - relative)
                throw new RangeError("Field lies outside its table");
            return table + relative;
        }

        public function get x():Number
        {
            const position:uint = fieldOffset(4, 4);
            if (!position) return 0;
            bytes.position = position;
            return bytes.readFloat();
        }

        public function get y():Number
        {
            const position:uint = fieldOffset(6, 4);
            if (!position) return 0;
            bytes.position = position;
            return bytes.readFloat();
        }

        public function unpack(destination:Point = null):Point
        {
            if (!destination)
                destination = new Point();

            destination.x = this.x;
            destination.y = this.y;
            return destination;
        }
    }
}
