// Code generated by as3flatc. DO NOT EDIT.
package example
{
    import as3flatbuffers.Builder;
    import flash.utils.ByteArray;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class Point
    {
        private static const BUILDER:as3flatbuffers.BuilderContext = new as3flatbuffers.BuilderContext();

        public var x:Number = 0;
        public var y:Number = 0;

        public static function reset(msg:Point):void
        {
            msg.x = 0;
            msg.y = 0;
        }

        public static function clone(source:Point):Point
        {
            if (!source)
                return null;

            const destination:Point = new Point();
            destination.x = source.x;
            destination.y = source.y;

            return destination;
        }

        /** Replace dst with packed bytes. Caller must select little-endian. Returns dst at position zero. */
        public static function pack(source:Point, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.BuilderContext = BUILDER;
            try
            {
                as3flatbuffers.Builder.begin(context, dst, true);
                as3flatbuffers.Builder.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Builder.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Point, context:as3flatbuffers.BuilderContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            as3flatbuffers.Builder.prepare(context, 2);
            as3flatbuffers.Builder.reserveVtable(context, 2);
            as3flatbuffers.Builder.prepare(context, 4);
            as3flatbuffers.Builder.startTable(context);
            if (source.x != 0)
            {
                as3flatbuffers.Builder.addFloat32(context, 0, source.x);
            }
            if (source.y != 0)
            {
                as3flatbuffers.Builder.addFloat32(context, 1, source.y);
            }
            return as3flatbuffers.Builder.endTable(context);
        }
    }
}
