// Code generated by as3flatc. DO NOT EDIT.
package example
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class PointView extends as3flatbuffers.TableView
    {
        public function get x():Number
        {
            const position:uint = fieldOffset(4, 4);
            if (!position)
                return 0;

            bytes.position = position;
            return bytes.readFloat();
        }

        public function get y():Number
        {
            const position:uint = fieldOffset(6, 4);
            if (!position)
                return 0;

            bytes.position = position;
            return bytes.readFloat();
        }

        public static function unpack(source:PointView, destination:Point = null):Point
        {
            if (!source || !source.bytes)
                throw new Error("View is not bound");

            const bytes:flash.utils.ByteArray = source.bytes;
            if (!destination)
                destination = new Point();

            const position0:uint = source.fieldOffset(4, 4);
            if (!position0)
            {
                destination.x = 0;
            }
            else
            {
                bytes.position = position0;
                destination.x = bytes.readFloat();
            }

            const position1:uint = source.fieldOffset(6, 4);
            if (!position1)
            {
                destination.y = 0;
            }
            else
            {
                bytes.position = position1;
                destination.y = bytes.readFloat();
            }
            return destination;
        }
    }
}
