// Code generated by as3flatc. DO NOT EDIT.
package example.chat
{
    import as3flatbuffers.Builder;
    import flash.utils.ByteArray;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class Chat
    {
        private static const BUILDER:as3flatbuffers.Builder = new as3flatbuffers.Builder();

        public var sender:String = null;
        public var message:String = null;

        public static function reset(msg:Chat):void
        {
            msg.sender = null;
            msg.message = null;
        }

        public static function clone(source:Chat):Chat
        {
            if (!source)
                return null;

            const destination:Chat = new Chat();
            destination.sender = source.sender;
            destination.message = source.message;

            return destination;
        }

        /** Replace dst with packed bytes. Caller must select little-endian. Returns dst at position zero. */
        public static function pack(source:Chat, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const builder:as3flatbuffers.Builder = BUILDER;
            try
            {
                builder.reset(dst, true);
                builder.finish(packInto(source, builder));
            }
            finally
            {
                builder.reset();
            }
            return dst;
        }

        /** Write into an active builder and return the absolute object offset. */
        public static function packInto(source:Chat, builder:as3flatbuffers.Builder):uint
        {
            if (!source || !builder)
                throw new ArgumentError("Source and builder must be non-null");

            builder.startTable(2, 4);
            const offset0:uint = source.sender != null ? builder.reserveOffset(0) : 0;
            const offset1:uint = source.message != null ? builder.reserveOffset(1) : 0;
            const table:uint = builder.endTable();
            if (offset0)
                builder.patchOffset(offset0, builder.createString(source.sender));
            if (offset1)
                builder.patchOffset(offset1, builder.createString(source.message));
            return table;
        }
    }
}
