// Code generated by as3flatc. DO NOT EDIT.
package example.chat
{
    import as3flatbuffers.Builder;
    import flash.utils.ByteArray;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class Chat
    {
        private static const BUILDER:as3flatbuffers.BuilderContext = new as3flatbuffers.BuilderContext();

        public var sender:String = null;
        public var message:String = null;

        public static function reset(msg:Chat):void
        {
            msg.sender = null;
            msg.message = null;
        }

        public static function clone(source:Chat):Chat
        {
            if (!source)
                return null;

            const destination:Chat = new Chat();
            destination.sender = source.sender;
            destination.message = source.message;

            return destination;
        }

        /** Replace dst with packed bytes. Caller must select little-endian. Returns dst at position zero. */
        public static function pack(source:Chat, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.BuilderContext = BUILDER;
            try
            {
                as3flatbuffers.Builder.reset(context, dst, true);
                as3flatbuffers.Builder.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Builder.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Chat, context:as3flatbuffers.BuilderContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            as3flatbuffers.Builder.startTable(context, 2, 4);
            const offset0:uint = source.sender != null ? as3flatbuffers.Builder.reserveOffset(context, 0) : 0;
            const offset1:uint = source.message != null ? as3flatbuffers.Builder.reserveOffset(context, 1) : 0;
            const table:uint = as3flatbuffers.Builder.endTable(context);
            if (offset0)
            {
                as3flatbuffers.Builder.prepare(context, 4);
                as3flatbuffers.Builder.writeString(context, offset0, source.sender);
            }
            if (offset1)
            {
                as3flatbuffers.Builder.prepare(context, 4);
                as3flatbuffers.Builder.writeString(context, offset1, source.message);
            }
            return table;
        }
    }
}
