// Code generated by as3flatc. DO NOT EDIT.
package example.chat
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class ChatView extends as3flatbuffers.TableView
    {
        public function get sender():String
        {
            return stringValue(4);
        }

        public function get message():String
        {
            return stringValue(6);
        }

        public static function unpack(source:ChatView, destination:Chat = null):Chat
        {
            if (!source || !source.bytes)
                throw new Error("View is not bound");

            const bytes:flash.utils.ByteArray = source.bytes;
            if (!destination)
                destination = new Chat();

            destination.sender = source.stringValue(4);

            destination.message = source.stringValue(6);
            return destination;
        }
    }
}
