// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;
    import example.geometry.Point;
    import example.geometry.PointView;

    /** Borrowed read-only view. Use the owned class unpack() API for independent values. */
    public final class PointMessageView extends as3flatbuffers.TableView
    {
        private const pointView:example.geometry.PointView = new example.geometry.PointView();

        public function get point():example.geometry.PointView
        {
            const position:uint = fieldOffset(4, 8);
            return position ? this.pointView.bind(bytes, position) : null;
        }
    }
}
