// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;
    import example.geometry.Point;
    import example.geometry.PointView;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class PointMessageView extends as3flatbuffers.TableView
    {
        private const pointView:example.geometry.PointView = new example.geometry.PointView();

        public function get point():example.geometry.PointView
        {
            const position:uint = fieldOffset(4, 8);
            return position ? this.pointView.bind(bytes, position) : null;
        }

        public static function unpack(source:PointMessageView, destination:PointMessage = null):PointMessage
        {
            if (!source || !source.bytes)
                throw new Error("View is not bound");

            const bytes:flash.utils.ByteArray = source.bytes;
            if (!destination)
                destination = new PointMessage();

            const pointViewPosition:uint = source.fieldOffset(4, 8);
            if (!pointViewPosition)
            {
                destination.point = null;
            }
            else
            {
                destination.point = example.geometry.PointView.unpack(source.pointView.bind(bytes, pointViewPosition), destination.point);
            }
            return destination;
        }
    }
}
