// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import as3flatbuffers.Builder;
    import example.geometry.Point;

    /** Owned mutable value. pack() returns an offset for Builder.finish(). */
    public final class PointMessage
    {
        public var point:example.geometry.Point = null;

        public function reset():void
        {
            this.point = null;
        }

        public static function clone(source:PointMessage):PointMessage
        {
            if (!source)
                return null;

            const destination:PointMessage = new PointMessage();
            destination.point = example.geometry.Point.clone(source.point);

            return destination;
        }

        public static function pack(source:PointMessage, builder:as3flatbuffers.Builder):uint
        {
            if (!source || !builder)
                throw new ArgumentError("Source and builder must be non-null");

            builder.startTable(1);
            if (source.point)
                builder.addStruct(0, example.geometry.Point.pack(source.point, builder));
            return builder.endTable();
        }
    }
}
