// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import as3flatbuffers.Builder;

    /** Owned inline struct. pack() writes at the current builder position. */
    public final class Point
    {
        public var x:Number = 0;
        public var y:Number = 0;

        public function reset():void
        {
            this.x = 0;
            this.y = 0;
        }

        public function copyFrom(source:Point):Point
        {
            this.x = source.x;
            this.y = source.y;
            return this;
        }

        public function clone():Point
        {
            return new Point().copyFrom(this);
        }

        public function pack(builder:as3flatbuffers.Builder):uint
        {
            builder.prepareStruct(8, 4);
            builder.putFloat32(this.y);
            builder.putFloat32(this.x);
            return builder.offset;
        }
    }
}
