// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import flash.utils.Endian;
    import flash.utils.ByteArray;
    import example.geometry.Point;
    import example.geometry.PointView;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class PointMessageView
    {
        private var bytes:flash.utils.ByteArray;
        private var table:uint;
        private var vtable:uint;
        private var vtableSize:uint;
        private var objectSize:uint;

        private const pointView:example.geometry.PointView = new example.geometry.PointView();

        /** Bind directly to a table's absolute byte position. */
        public function bind(input:flash.utils.ByteArray, offset:uint):PointMessageView
        {
            bytes = null;
            if (!input)
                throw new ArgumentError("Input must be non-null");
            if (offset > input.length || input.length - offset < 4)
                throw new RangeError("Truncated table");

            input.endian = Endian.LITTLE_ENDIAN;
            input.position = offset;
            const voffset:Number = Number(offset) - input.readInt();
            if (voffset < 0 || voffset > input.length - 4)
                throw new RangeError("Invalid vtable offset");

            input.position = uint(voffset);
            const vtSize:uint = input.readUnsignedShort();
            const objSize:uint = input.readUnsignedShort();
            if (vtSize < 4 || (vtSize & 1) || vtSize > input.length - voffset ||
                    objSize < 4 || objSize > input.length - offset)
                throw new RangeError("Invalid table size");

            table = offset;
            vtable = uint(voffset);
            vtableSize = vtSize;
            objectSize = objSize;
            bytes = input;
            return this;
        }

        [Inline]
        private final function fieldOffset(slot:uint, width:uint):uint
        {
            if (!bytes)
                throw new Error("View is not bound");
            if (slot >= vtableSize)
                return 0;

            bytes.position = vtable + slot;
            const relative:uint = bytes.readUnsignedShort();
            if (!relative)
                return 0;
            if (relative < 4 || relative > objectSize || width > objectSize - relative)
                throw new RangeError("Field lies outside its table");

            return table + relative;
        }

        public function get point():example.geometry.PointView
        {
            const position:uint = fieldOffset(4, 8);
            return position ? this.pointView.bind(bytes, position) : null;
        }

        public static function unpack(source:PointMessageView, destination:PointMessage = null):PointMessage
        {
            if (!source || !source.bytes)
                throw new Error("View is not bound");

            const bytes:flash.utils.ByteArray = source.bytes;
            if (!destination)
                destination = new PointMessage();

            const pointViewPosition:uint = source.fieldOffset(4, 8);
            if (!pointViewPosition)
            {
                destination.point = null;
            }
            else
            {
                destination.point = example.geometry.PointView.unpack(source.pointView.bind(bytes, pointViewPosition), destination.point);
            }
            return destination;
        }
    }
}
