// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import as3flatbuffers.Builder;

    /** Owned inline struct. pack() writes at the current builder position. */
    public final class Point
    {
        public var x:Number = 0;
        public var y:Number = 0;

        public function reset():void
        {
            this.x = 0;
            this.y = 0;
        }

        public static function clone(source:Point):Point
        {
            if (!source)
                return null;

            const destination:Point = new Point();
            destination.x = source.x;
            destination.y = source.y;

            return destination;
        }

        public static function pack(source:Point, builder:as3flatbuffers.Builder):uint
        {
            if (!source || !builder)
                throw new ArgumentError("Source and builder must be non-null");

            builder.prepareStruct(8, 4);
            builder.putFloat32(source.y);
            builder.putFloat32(source.x);
            return builder.offset;
        }
    }
}
