// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import flash.utils.Endian;
    import flash.utils.ByteArray;

    /** Borrowed inline struct. bind() takes the struct's absolute byte offset. */
    public final class PointView
    {
        private var bytes:flash.utils.ByteArray;
        private var base:uint;

        public function bind(input:flash.utils.ByteArray, offset:uint):PointView
        {
            bytes = null;
            if (!input)
                throw new ArgumentError("Input must be non-null");
            if (offset > input.length || 8 > input.length - offset)
                throw new RangeError("Truncated struct");

            input.endian = Endian.LITTLE_ENDIAN;
            base = offset;
            bytes = input;
            return this;
        }

        public function get x():Number
        {
            if (!bytes)
                throw new Error("View is not bound");

            bytes.position = base + 0;
            return bytes.readFloat();
        }

        public function get y():Number
        {
            if (!bytes)
                throw new Error("View is not bound");

            bytes.position = base + 4;
            return bytes.readFloat();
        }

        public static function unpack(source:PointView, destination:Point = null):Point
        {
            if (!source || !source.bytes)
                throw new Error("View is not bound");

            const bytes:flash.utils.ByteArray = source.bytes;
            const base:uint = source.base;
            if (!destination)
                destination = new Point();

            bytes.position = base + 0;
            destination.x = bytes.readFloat();

            bytes.position = base + 4;
            destination.y = bytes.readFloat();
            return destination;
        }
    }
}
