// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import as3flatbuffers.Builder;
    import flash.utils.ByteArray;
    import example.geometry.Point;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class PointMessage
    {
        private static const BUILDER:as3flatbuffers.Builder = new as3flatbuffers.Builder();

        public var point:example.geometry.Point = null;

        public static function reset(msg:PointMessage):void
        {
            msg.point = null;
        }

        public static function clone(source:PointMessage):PointMessage
        {
            if (!source)
                return null;

            const destination:PointMessage = new PointMessage();
            destination.point = example.geometry.Point.clone(source.point);

            return destination;
        }

        /** Replace dst with packed bytes. Caller must select little-endian. Returns dst at position zero. */
        public static function pack(source:PointMessage, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const builder:as3flatbuffers.Builder = BUILDER;
            try
            {
                builder.reset(dst, true);
                builder.finish(packInto(source, builder));
            }
            finally
            {
                builder.reset();
            }
            return dst;
        }

        /** Write into an active builder and return the absolute object offset. */
        public static function packInto(source:PointMessage, builder:as3flatbuffers.Builder):uint
        {
            if (!source || !builder)
                throw new ArgumentError("Source and builder must be non-null");

            builder.startTable(1, 4);
            if (source.point)
                builder.addStruct(0, example.geometry.Point.packInto(source.point, builder));
            return builder.endTable();
        }
    }
}
