// Code generated by as3flatc. DO NOT EDIT.
package example.geometry
{
    import flash.utils.Endian;
    import flash.utils.ByteArray;

    /** Borrowed inline struct. bind() takes the struct's absolute byte offset. */
    public final class TransformView
    {
        private var bytes:flash.utils.ByteArray;
        private var base:uint;

        public function bind(input:flash.utils.ByteArray, offset:uint):TransformView
        {
            bytes = null;
            if (!input)
                throw new ArgumentError("Input must be non-null");
            if (offset > input.length || 64 > input.length - offset)
                throw new RangeError("Truncated struct");

            input.endian = Endian.LITTLE_ENDIAN;
            base = offset;
            bytes = input;
            return this;
        }

        public function get matrixLength():uint
        {
            return 16;
        }

        public function matrix(index:uint):Number
        {
            if (index >= 16)
                throw new RangeError("Array index is out of range");
            bytes.position = base + 0 + index * 4;
            return bytes.readFloat();
        }
    }
}
