// Code generated by as3flatc. DO NOT EDIT.
package example.protocol
{
    import flash.utils.Endian;
    import flash.utils.ByteArray;

    /** Borrowed inline struct. bind() takes the struct's absolute byte offset. */
    public final class DamageView
    {
        private var bytes:flash.utils.ByteArray;
        private var base:uint;

        public function bind(input:flash.utils.ByteArray, offset:uint):DamageView
        {
            bytes = null;
            if (!input)
                throw new ArgumentError("Input must be non-null");
            if (offset > input.length || 4 > input.length - offset)
                throw new RangeError("Truncated struct");

            input.endian = Endian.LITTLE_ENDIAN;
            base = offset;
            bytes = input;
            return this;
        }

        public function get amount():int
        {
            if (!bytes)
                throw new Error("View is not bound");

            bytes.position = base + 0;
            return bytes.readInt();
        }
    }
}
