// Code generated by as3flatc. DO NOT EDIT.
package example.protocol
{
    import as3flatbuffers.Pack;
    import as3flatbuffers.Unpack;
    import as3flatbuffers.UnpackContext;
    import avm2.intrinsics.memory.*;
    import flash.utils.ByteArray;

    /** Owned inline struct. pack() writes raw struct bytes into the destination. */
    public final class Damage
    {
        private static const PACK:as3flatbuffers.PackContext = new as3flatbuffers.PackContext();
        private static const UNPACK:as3flatbuffers.UnpackContext = new as3flatbuffers.UnpackContext();

        public var amount:int = 0;

        public static function reset(msg:Damage):void
        {
            msg.amount = 0;
        }

        public static function clone(source:Damage):Damage
        {
            if (!source)
                return null;

            const destination:Damage = new Damage();
            destination.amount = source.amount;

            return destination;
        }

        /** Replace dst with packed bytes. Writes little-endian without changing dst.endian. Returns dst at position zero. */
        public static function pack(source:Damage, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.PackContext = PACK;
            try
            {
                as3flatbuffers.Pack.begin(context, dst, false);
                as3flatbuffers.Pack.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Pack.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Damage, context:as3flatbuffers.PackContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            const start:uint = as3flatbuffers.Pack.prepareStruct(context, 4, 4);
            si32(source.amount, start + 0);
            return start;
        }

        /** Decode raw struct bytes at offset into a new or reused owned value. */
        public static function unpack(bytes:flash.utils.ByteArray, destination:Damage = null, offset:uint = 0):Damage
        {
            const context:as3flatbuffers.UnpackContext = UNPACK;
            const previous:flash.utils.ByteArray = as3flatbuffers.Unpack.begin(context, bytes);
            try
            {
                destination = unpackFrom(context, offset, destination);
            }
            finally
            {
                as3flatbuffers.Unpack.end(context, previous);
            }
            return destination;
        }

        /** Internal generated entry point; context must already own domain memory. */
        public static function unpackFrom(context:as3flatbuffers.UnpackContext, base:uint, destination:Damage):Damage
        {
            as3flatbuffers.Unpack.struct(context, base, 4);
            if (!destination)
                destination = new Damage();

            destination.amount = li32(base + 0);
            return destination;
        }
    }
}
