// Code generated by as3flatc. DO NOT EDIT.
package example.protocol
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class MoveView extends as3flatbuffers.TableView
    {
        public function get x():Number
        {
            const position:uint = fieldOffset(4, 4);
            if (!position)
                return 0;

            bytes.position = position;
            return bytes.readFloat();
        }

        public function get y():Number
        {
            const position:uint = fieldOffset(6, 4);
            if (!position)
                return 0;

            bytes.position = position;
            return bytes.readFloat();
        }
    }
}
