// Code generated by as3flatc. DO NOT EDIT.
package example.protocol
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;
    import example.protocol.Payload;
    import example.protocol.PayloadView;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class PacketView extends as3flatbuffers.TableView
    {
        private var payloadView:example.protocol.PayloadView;

        public function get payload():example.protocol.PayloadView
        {
            if (!this.payloadView)
                this.payloadView = new example.protocol.PayloadView();

            const tag:uint = fieldOffset(4, 1);
            var type:uint = 0;
            if (tag)
            {
                bytes.position = tag;
                type = bytes.readUnsignedByte();
            }
            const reference:uint = fieldOffset(6, 4);
            return this.payloadView.bind(bytes, type, reference);
        }
    }
}
