// Code generated by as3flatc. DO NOT EDIT.
package example.protocol
{
    import as3flatbuffers.Pack;
    import as3flatbuffers.Unpack;
    import as3flatbuffers.UnpackContext;
    import avm2.intrinsics.memory.*;
    import flash.utils.ByteArray;
    import example.protocol.Payload;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class Packet
    {
        private static const PACK:as3flatbuffers.PackContext = new as3flatbuffers.PackContext();
        private static const UNPACK:as3flatbuffers.UnpackContext = new as3flatbuffers.UnpackContext();

        public var payload:example.protocol.Payload = new example.protocol.Payload();

        public static function reset(msg:Packet):void
        {
            example.protocol.Payload.reset(msg.payload);
        }

        public static function clone(source:Packet):Packet
        {
            if (!source)
                return null;

            const destination:Packet = new Packet();
            destination.payload = example.protocol.Payload.clone(source.payload);

            return destination;
        }

        /** Replace dst with packed bytes. Writes little-endian without changing dst.endian. Returns dst at position zero. */
        public static function pack(source:Packet, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.PackContext = PACK;
            try
            {
                as3flatbuffers.Pack.begin(context, dst, true);
                as3flatbuffers.Pack.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Pack.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Packet, context:as3flatbuffers.PackContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            as3flatbuffers.Pack.ensure(context, 24);
            as3flatbuffers.Pack.prepare(context, 2);
            as3flatbuffers.Pack.reserveVtable(context, 2);
            as3flatbuffers.Pack.prepare(context, 4);
            as3flatbuffers.Pack.startTable(context);
            example.protocol.Payload.validate(source.payload);
            var offset1:uint = 0;
            if (source.payload.type)
            {
                as3flatbuffers.Pack.addUint8(context, 0, source.payload.type);
                as3flatbuffers.Pack.prepare(context, 4);
                offset1 = as3flatbuffers.Pack.reserveOffset(context, 1);
            }
            const table:uint = as3flatbuffers.Pack.endTable(context);
            if (offset1)
            {
                example.protocol.Payload.packInto(source.payload, context, offset1);
            }
            return table;
        }

        /** Decode a FlatBuffer whose root-offset word starts at offset. */
        public static function unpack(bytes:flash.utils.ByteArray, destination:Packet = null, offset:uint = 0):Packet
        {
            const context:as3flatbuffers.UnpackContext = UNPACK;
            const previous:flash.utils.ByteArray = as3flatbuffers.Unpack.begin(context, bytes);
            try
            {
                destination = unpackFrom(context, as3flatbuffers.Unpack.root(context, offset), destination);
            }
            finally
            {
                as3flatbuffers.Unpack.end(context, previous);
            }
            return destination;
        }

        /** Internal generated entry point; context must already own domain memory. */
        public static function unpackFrom(context:as3flatbuffers.UnpackContext, base:uint, destination:Packet):Packet
        {
            const vtable:uint = as3flatbuffers.Unpack.vtable(context, base);
            const vtableSize:uint = li16(vtable);
            const objectSize:uint = li16(vtable + 2);
            if (!destination)
                destination = new Packet();

            const tag1:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 4, 1);
            const field1:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 6, 4);
            destination.payload = example.protocol.Payload.unpackFrom(context, tag1 ? li8(tag1) : 0, field1, destination.payload);
            return destination;
        }
    }
}
