// Code generated by as3flatc. DO NOT EDIT.
package example.protocol
{
    import flash.utils.ByteArray;
    import flash.utils.Endian;
    import example.protocol.Damage;
    import example.protocol.DamageView;
    import example.protocol.Move;
    import example.protocol.MoveView;

    /** Borrowed tagged union. Only the selected member getter returns a value. */
    public final class PayloadView
    {
        private var bytes:ByteArray;
        private var tag:uint;
        private var position:uint;
        private var moveView:example.protocol.MoveView;
        private var damageView:example.protocol.DamageView;

        /** Bind a tag and the absolute position of its payload-offset word (zero if absent). */
        public function bind(input:ByteArray, type:uint, reference:uint):PayloadView
        {
            bytes = null;
            tag = 0;
            position = 0;
            if (!input)
                throw new ArgumentError("Input must be non-null");
            input.endian = Endian.LITTLE_ENDIAN;
            var width:uint = 0;
            switch (type)
            {
                case Payload.NONE:
                    break;
                case Payload.MOVE:
                    width = 4;
                    break;
                case Payload.DAMAGE:
                    width = 4;
                    break;
                case Payload.TEXT:
                    width = 4;
                    break;
                default:
                    throw new RangeError("Unknown union tag");
            }
            var relative:uint = 0;
            if (reference)
            {
                if (Number(reference) + 4 > input.length)
                    throw new RangeError("Truncated union reference");
                input.position = reference;
                relative = input.readUnsignedInt();
            }
            if (type == Payload.NONE)
            {
                if (relative)
                    throw new RangeError("NONE union has a payload");
            }
            else
            {
                if (!reference || relative < 4 || Number(reference) + relative + width > input.length)
                    throw new RangeError("Invalid union payload offset");
                position = reference + relative;
            }
            tag = type;
            bytes = input;
            return this;
        }

        public function get type():uint
        {
            return tag;
        }

        public function get move():example.protocol.MoveView
        {
            if (tag != Payload.MOVE)
                return null;
            if (!this.moveView)
                this.moveView = new example.protocol.MoveView();

            this.moveView.bind(bytes, position);
            return this.moveView;
        }

        public function get damage():example.protocol.DamageView
        {
            if (tag != Payload.DAMAGE)
                return null;
            if (!this.damageView)
                this.damageView = new example.protocol.DamageView();

            this.damageView.bind(bytes, position);
            return this.damageView;
        }

        public function get text():String
        {
            if (tag != Payload.TEXT)
                return null;
            bytes.position = position;
            const length:uint = bytes.readUnsignedInt();
            const start:uint = bytes.position;
            if (length >= bytes.length - start)
                throw new RangeError("Truncated union string");
            if (bytes[start + length] != 0)
                throw new RangeError("String terminator must be zero");
            return bytes.readUTFBytes(length);
        }
    }
}
