// Code generated by as3flatc. DO NOT EDIT.
package example.protocol
{
    import avm2.intrinsics.memory.*;
    import as3flatbuffers.Pack;
    import as3flatbuffers.PackContext;
    import as3flatbuffers.Unpack;
    import as3flatbuffers.UnpackContext;
    import example.protocol.Damage;
    import example.protocol.Move;

    /** Tagged union. Inactive members remain cached for reuse. */
    public final class Payload
    {
        public static const NONE:uint = 0;
        public static const MOVE:uint = 1;
        public static const DAMAGE:uint = 2;
        public static const TEXT:uint = 3;

        public var type:uint = NONE;
        public var move:example.protocol.Move = null;
        public var damage:example.protocol.Damage = null;
        public var text:String = null;

        /** Clear cached values in place and select NONE. */
        public static function reset(msg:Payload):void
        {
            msg.type = NONE;
            if (msg.move)
                example.protocol.Move.reset(msg.move);
            if (msg.damage)
                example.protocol.Damage.reset(msg.damage);
            msg.text = null;
        }

        public static function clone(source:Payload):Payload
        {
            if (!source)
                return null;
            const destination:Payload = new Payload();
            destination.type = source.type;
            destination.move = example.protocol.Move.clone(source.move);
            destination.damage = example.protocol.Damage.clone(source.damage);
            destination.text = source.text;
            return destination;
        }

        /** Validate the selected member before writing the parent table. */
        public static function validate(source:Payload):void
        {
            if (!source)
                throw new ArgumentError("Union must be non-null");
            switch (source.type)
            {
                case NONE:
                    return;
                case MOVE:
                    if (source.move == null)
                        throw new ArgumentError("Selected union member move must be non-null");
                    return;
                case DAMAGE:
                    if (source.damage == null)
                        throw new ArgumentError("Selected union member damage must be non-null");
                    return;
                case TEXT:
                    if (source.text == null)
                        throw new ArgumentError("Selected union member text must be non-null");
                    return;
                default:
                    throw new ArgumentError("Unknown union tag");
            }
        }

        /** Internal: write a validated active member after closing its parent table. */
        public static function packInto(source:Payload, context:as3flatbuffers.PackContext, reference:uint):void
        {
            switch (source.type)
            {
                case MOVE:
                    const position1:uint = example.protocol.Move.packInto(source.move, context);
                    as3flatbuffers.Pack.patchOffset(context, reference, position1);
                    return;
                case DAMAGE:
                    const position2:uint = example.protocol.Damage.packInto(source.damage, context);
                    as3flatbuffers.Pack.patchOffset(context, reference, position2);
                    return;
                case TEXT:
                    as3flatbuffers.Pack.prepare(context, 4);
                    as3flatbuffers.Pack.writeString(context, reference, source.text);
                    return;
                default:
                    throw new ArgumentError("Expected an active union member");
            }
        }

        /** Internal: decode the selected member and retain inactive cached objects. */
        public static function unpackFrom(context:as3flatbuffers.UnpackContext, tag:uint, reference:uint, destination:Payload):Payload
        {
            if (!destination)
                destination = new Payload();
            switch (tag)
            {
                case NONE:
                    if (reference && li32(reference))
                        throw new RangeError("NONE union has a payload");
                    break;
                case MOVE:
                    const position1:uint = as3flatbuffers.Unpack.unionOffset(context, reference, 4);
                    destination.move = example.protocol.Move.unpackFrom(context, position1, destination.move);
                    break;
                case DAMAGE:
                    const position2:uint = as3flatbuffers.Unpack.unionOffset(context, reference, 4);
                    destination.damage = example.protocol.Damage.unpackFrom(context, position2, destination.damage);
                    break;
                case TEXT:
                    const position3:uint = as3flatbuffers.Unpack.unionOffset(context, reference, 4);
                    destination.text = as3flatbuffers.Unpack.stringValue(context, reference);
                    break;
                default:
                    throw new RangeError("Unknown union tag");
            }
            destination.type = tag;
            return destination;
        }
    }
}
