// Code generated by as3flatc. DO NOT EDIT.
package example.inventory
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;
    import example.inventory.Item;
    import example.inventory.ItemView;
    import example.inventory.Position;
    import example.inventory.PositionView;

    /** Borrowed read-only view. Use the owned class unpack() API for independent values. */
    public final class InventoryView extends as3flatbuffers.TableView
    {
        private var itemsView:example.inventory.ItemView;

        private const pathView:example.inventory.PositionView = new example.inventory.PositionView();

        public function get itemsLength():uint
        {
            const position:uint = vectorOffset(4, 4);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        /** Returns a cached view rebound on each access. */
        public function items(index:uint):example.inventory.ItemView
        {
            const vector:uint = vectorOffset(4, 4);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 4;
            if (!this.itemsView)
                this.itemsView = new example.inventory.ItemView();

            const child:uint = referenceAt(position);
            this.itemsView.bind(bytes, child);
            return this.itemsView;
        }

        /** Binary search of an ascending key-sorted vector. Returns the same cached view as indexed access, or null. */
        public function itemsByKey(key:uint):example.inventory.ItemView
        {
            const vector:uint = vectorOffset(4, 4);
            if (!vector)
                return null;
            if (!this.itemsView)
                this.itemsView = new example.inventory.ItemView();

            bytes.position = vector;
            var span:uint = bytes.readUnsignedInt();
            var start:uint = 0;
            while (span)
            {
                const middle:uint = span >>> 1;
                const position:uint = vector + 4 + (start + middle) * 4;
                const child:uint = referenceAt(position);
                this.itemsView.bind(bytes, child);
                const comparison:int = this.itemsView.compareKey(key);
                if (comparison < 0)
                {
                    start += middle + 1;
                    span -= middle + 1;
                }
                else if (comparison > 0)
                    span = middle;
                else
                    return this.itemsView;
            }
            return null;
        }

        public function get pathLength():uint
        {
            const position:uint = vectorOffset(6, 8);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        /** Returns a cached view rebound on each access. */
        public function path(index:uint):example.inventory.PositionView
        {
            const vector:uint = vectorOffset(6, 8);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 8;
            return this.pathView.bind(bytes, position);
        }

        public function get tagsLength():uint
        {
            const position:uint = vectorOffset(8, 4);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        public function tags(index:uint):String
        {
            const vector:uint = vectorOffset(8, 4);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 4;
            return stringAt(position);
        }

        public function get scoresLength():uint
        {
            const position:uint = vectorOffset(10, 4);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        public function scores(index:uint):int
        {
            const vector:uint = vectorOffset(10, 4);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 4;
            bytes.position = position;
            return bytes.readInt();
        }
    }
}
