// Code generated by as3flatc. DO NOT EDIT.
package example.inventory
{
    import as3flatbuffers.Pack;
    import as3flatbuffers.Unpack;
    import as3flatbuffers.UnpackContext;
    import avm2.intrinsics.memory.*;
    import flash.utils.ByteArray;
    import example.inventory.Item;
    import example.inventory.Position;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class Inventory
    {
        private static const PACK:as3flatbuffers.PackContext = new as3flatbuffers.PackContext();
        private static const UNPACK:as3flatbuffers.UnpackContext = new as3flatbuffers.UnpackContext();

        public var items:Vector.<example.inventory.Item> = new Vector.<example.inventory.Item>();
        public var path:Vector.<example.inventory.Position> = new Vector.<example.inventory.Position>();
        public var tags:Vector.<String> = new Vector.<String>();
        public var scores:Vector.<int> = new Vector.<int>();

        public static function reset(msg:Inventory):void
        {
            msg.items.length = 0;
            msg.path.length = 0;
            msg.tags.length = 0;
            msg.scores.length = 0;
        }

        public static function clone(source:Inventory):Inventory
        {
            if (!source)
                return null;

            const destination:Inventory = new Inventory();
            destination.items.length = source.items.length;
            for (var index0:uint = 0; index0 < source.items.length; index0++)
            {
                destination.items[index0] = example.inventory.Item.clone(source.items[index0]);
            }
            destination.path.length = source.path.length;
            for (var index1:uint = 0; index1 < source.path.length; index1++)
            {
                destination.path[index1] = example.inventory.Position.clone(source.path[index1]);
            }
            destination.tags = source.tags.concat();
            destination.scores = source.scores.concat();

            return destination;
        }

        /** Replace dst with packed bytes. Caller must select little-endian. Returns dst at position zero. */
        public static function pack(source:Inventory, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.PackContext = PACK;
            try
            {
                as3flatbuffers.Pack.begin(context, dst, true);
                as3flatbuffers.Pack.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Pack.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Inventory, context:as3flatbuffers.PackContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            as3flatbuffers.Pack.prepare(context, 2);
            as3flatbuffers.Pack.reserveVtable(context, 4);
            as3flatbuffers.Pack.prepare(context, 4);
            as3flatbuffers.Pack.startTable(context);
            const offset0:uint = source.items.length ? as3flatbuffers.Pack.reserveOffset(context, 0) : 0;
            const offset1:uint = source.path.length ? as3flatbuffers.Pack.reserveOffset(context, 1) : 0;
            const offset2:uint = source.tags.length ? as3flatbuffers.Pack.reserveOffset(context, 2) : 0;
            const offset3:uint = source.scores.length ? as3flatbuffers.Pack.reserveOffset(context, 3) : 0;
            const table:uint = as3flatbuffers.Pack.endTable(context);
            if (offset0)
            {
                const bytes0:flash.utils.ByteArray = as3flatbuffers.Pack.prepareVector(context, 4);
                const vector0:uint = as3flatbuffers.Pack.startVector(context, source.items.length);
                as3flatbuffers.Pack.patchOffset(context, offset0, vector0);
                const data0:uint = bytes0.position;
                for (var reserve0:uint = 0; reserve0 < source.items.length; reserve0++)
                    bytes0.writeUnsignedInt(0);
                for (var index0:uint = 0; index0 < source.items.length; index0++)
                {
                    if (source.items[index0] == null)
                        throw new ArgumentError("items elements must be non-null");
                    const child0:uint = example.inventory.Item.packInto(source.items[index0], context);
                    as3flatbuffers.Pack.patchOffset(context, data0 + index0 * 4, child0);
                }
            }
            if (offset1)
            {
                const bytes1:flash.utils.ByteArray = as3flatbuffers.Pack.prepareVector(context, 4);
                const vector1:uint = as3flatbuffers.Pack.startVector(context, source.path.length);
                as3flatbuffers.Pack.patchOffset(context, offset1, vector1);
                for (var index1:uint = 0; index1 < source.path.length; index1++)
                {
                    if (source.path[index1] == null)
                        throw new ArgumentError("path elements must be non-null");
                    example.inventory.Position.packInto(source.path[index1], context);
                }
            }
            if (offset2)
            {
                const bytes2:flash.utils.ByteArray = as3flatbuffers.Pack.prepareVector(context, 4);
                const vector2:uint = as3flatbuffers.Pack.startVector(context, source.tags.length);
                as3flatbuffers.Pack.patchOffset(context, offset2, vector2);
                const data2:uint = bytes2.position;
                for (var reserve2:uint = 0; reserve2 < source.tags.length; reserve2++)
                    bytes2.writeUnsignedInt(0);
                for (var index2:uint = 0; index2 < source.tags.length; index2++)
                {
                    if (source.tags[index2] == null)
                        throw new ArgumentError("tags elements must be non-null");
                    as3flatbuffers.Pack.prepare(context, 4);
                    as3flatbuffers.Pack.writeString(context, data2 + index2 * 4, source.tags[index2]);
                }
            }
            if (offset3)
            {
                const bytes3:flash.utils.ByteArray = as3flatbuffers.Pack.prepareVector(context, 4);
                const vector3:uint = as3flatbuffers.Pack.startVector(context, source.scores.length);
                as3flatbuffers.Pack.patchOffset(context, offset3, vector3);
                for (var index3:uint = 0; index3 < source.scores.length; index3++)
                {
                    bytes3.writeInt(source.scores[index3]);
                }
            }
            return table;
        }

        /** Decode a FlatBuffer whose root-offset word starts at offset. */
        public static function unpack(bytes:flash.utils.ByteArray, destination:Inventory = null, offset:uint = 0):Inventory
        {
            const context:as3flatbuffers.UnpackContext = UNPACK;
            const previous:flash.utils.ByteArray = as3flatbuffers.Unpack.begin(context, bytes);
            try
            {
                destination = unpackFrom(context, as3flatbuffers.Unpack.root(context, offset), destination);
            }
            finally
            {
                as3flatbuffers.Unpack.end(context, previous);
            }
            return destination;
        }

        /** Internal generated entry point; context must already own domain memory. */
        public static function unpackFrom(context:as3flatbuffers.UnpackContext, base:uint, destination:Inventory):Inventory
        {
            const vtable:uint = as3flatbuffers.Unpack.vtable(context, base);
            const vtableSize:uint = li16(vtable);
            const objectSize:uint = li16(vtable + 2);
            if (!destination)
                destination = new Inventory();

            const field0:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 4, 4);
            const vector0:uint = as3flatbuffers.Unpack.vector(context, field0, 4);
            const count0:uint = vector0 ? uint(li32(vector0)) : 0;
            destination.items.length = count0;

            for (var index0:uint = 0; index0 < count0; index0++)
            {
                const element0:uint = vector0 + 4 + index0 * 4;
                const child0:uint = as3flatbuffers.Unpack.tableOffset(context, element0);
                destination.items[index0] = example.inventory.Item.unpackFrom(context, child0, destination.items[index0]);
            }

            const field1:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 6, 4);
            const vector1:uint = as3flatbuffers.Unpack.vector(context, field1, 8);
            const count1:uint = vector1 ? uint(li32(vector1)) : 0;
            destination.path.length = count1;

            for (var index1:uint = 0; index1 < count1; index1++)
            {
                const element1:uint = vector1 + 4 + index1 * 8;
                destination.path[index1] = example.inventory.Position.unpackFrom(context, element1, destination.path[index1]);
            }

            const field2:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 8, 4);
            const vector2:uint = as3flatbuffers.Unpack.vector(context, field2, 4);
            const count2:uint = vector2 ? uint(li32(vector2)) : 0;
            destination.tags.length = count2;

            for (var index2:uint = 0; index2 < count2; index2++)
            {
                const element2:uint = vector2 + 4 + index2 * 4;
                destination.tags[index2] = as3flatbuffers.Unpack.stringValue(context, element2);
            }

            const field3:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 10, 4);
            const vector3:uint = as3flatbuffers.Unpack.vector(context, field3, 4);
            const count3:uint = vector3 ? uint(li32(vector3)) : 0;
            destination.scores.length = count3;

            for (var index3:uint = 0; index3 < count3; index3++)
            {
                const element3:uint = vector3 + 4 + index3 * 4;
                destination.scores[index3] = li32(element3);
            }
            return destination;
        }
    }
}
