// Code generated by as3flatc. DO NOT EDIT.
package example.inventory
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;
    import example.inventory.Item;
    import example.inventory.ItemView;
    import example.inventory.Position;
    import example.inventory.PositionView;

    /** Borrowed read-only view; unpack() produces independent owned values. */
    public final class InventoryView extends as3flatbuffers.TableView
    {
        private var itemsView:example.inventory.ItemView;

        private const pathView:example.inventory.PositionView = new example.inventory.PositionView();

        public function get itemsLength():uint
        {
            const position:uint = vectorOffset(4, 4);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        /** Returns a cached view rebound on each access. */
        public function items(index:uint):example.inventory.ItemView
        {
            const vector:uint = vectorOffset(4, 4);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 4;
            if (!this.itemsView)
                this.itemsView = new example.inventory.ItemView();

            const child:uint = referenceAt(position);
            this.itemsView.bind(bytes, child);
            return this.itemsView;
        }

        public function get pathLength():uint
        {
            const position:uint = vectorOffset(6, 8);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        /** Returns a cached view rebound on each access. */
        public function path(index:uint):example.inventory.PositionView
        {
            const vector:uint = vectorOffset(6, 8);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 8;
            return this.pathView.bind(bytes, position);
        }

        public function get tagsLength():uint
        {
            const position:uint = vectorOffset(8, 4);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        public function tags(index:uint):String
        {
            const vector:uint = vectorOffset(8, 4);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 4;
            return stringAt(position);
        }

        public function get scoresLength():uint
        {
            const position:uint = vectorOffset(10, 4);
            if (!position)
                return 0;
            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        public function scores(index:uint):int
        {
            const vector:uint = vectorOffset(10, 4);
            if (!vector)
                throw new RangeError("Vector index is out of range");
            bytes.position = vector;
            if (index >= bytes.readUnsignedInt())
                throw new RangeError("Vector index is out of range");
            const position:uint = vector + 4 + index * 4;
            bytes.position = position;
            return bytes.readInt();
        }
    }
}
