// Code generated by as3flatc. DO NOT EDIT.
package example.inventory
{
    import as3flatbuffers.TableView;
    import flash.utils.ByteArray;

    /** Borrowed read-only view. Use the owned class unpack() API for independent values. */
    public final class ItemView extends as3flatbuffers.TableView
    {
        public function get id():uint
        {
            const position:uint = fieldOffset(4, 4);
            if (!position)
                return 0;

            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        public function get quantity():uint
        {
            const position:uint = fieldOffset(6, 4);
            if (!position)
                return 1;

            bytes.position = position;
            return bytes.readUnsignedInt();
        }

        public function get rarity():uint
        {
            const position:uint = fieldOffset(8, 1);
            if (!position)
                return 0;

            bytes.position = position;
            return bytes.readUnsignedByte();
        }

        /** Internal comparison; string queries are UTF-8 bytes and numeric queries are normalized. */
        public function compareKey(key:uint):int
        {
            const value:uint = this.id;
            return value < key ? -1 : (value > key ? 1 : 0);
        }
    }
}
