// Code generated by as3flatc. DO NOT EDIT.
package example.inventory
{
    import as3flatbuffers.Pack;
    import as3flatbuffers.Unpack;
    import as3flatbuffers.UnpackContext;
    import avm2.intrinsics.memory.*;
    import flash.utils.ByteArray;

    /** Owned mutable value. pack() writes a complete FlatBuffer into the destination. */
    public final class Item
    {
        private static const PACK:as3flatbuffers.PackContext = new as3flatbuffers.PackContext();
        private static const UNPACK:as3flatbuffers.UnpackContext = new as3flatbuffers.UnpackContext();

        public var id:uint = 0;
        public var quantity:uint = 1;
        public var rarity:uint = 0;

        public static function reset(msg:Item):void
        {
            msg.id = 0;
            msg.quantity = 1;
            msg.rarity = 0;
        }

        public static function clone(source:Item):Item
        {
            if (!source)
                return null;

            const destination:Item = new Item();
            destination.id = source.id;
            destination.quantity = source.quantity;
            destination.rarity = source.rarity;

            return destination;
        }

        /** Replace dst with packed bytes. Writes little-endian without changing dst.endian. Returns dst at position zero. */
        public static function pack(source:Item, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.PackContext = PACK;
            try
            {
                as3flatbuffers.Pack.begin(context, dst, true);
                as3flatbuffers.Pack.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Pack.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Item, context:as3flatbuffers.PackContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            as3flatbuffers.Pack.ensure(context, 33);
            as3flatbuffers.Pack.prepare(context, 2);
            as3flatbuffers.Pack.reserveVtable(context, 3);
            as3flatbuffers.Pack.prepare(context, 4);
            as3flatbuffers.Pack.startTable(context);
            if (source.id != 0)
            {
                as3flatbuffers.Pack.addUint32(context, 0, source.id);
            }
            if (source.quantity != 1)
            {
                as3flatbuffers.Pack.addUint32(context, 1, source.quantity);
            }
            if (source.rarity != 0)
            {
                as3flatbuffers.Pack.addUint8(context, 2, source.rarity);
            }
            return as3flatbuffers.Pack.endTable(context);
        }

        /** Decode a FlatBuffer whose root-offset word starts at offset. */
        public static function unpack(bytes:flash.utils.ByteArray, destination:Item = null, offset:uint = 0):Item
        {
            const context:as3flatbuffers.UnpackContext = UNPACK;
            const previous:flash.utils.ByteArray = as3flatbuffers.Unpack.begin(context, bytes);
            try
            {
                destination = unpackFrom(context, as3flatbuffers.Unpack.root(context, offset), destination);
            }
            finally
            {
                as3flatbuffers.Unpack.end(context, previous);
            }
            return destination;
        }

        /** Internal generated entry point; context must already own domain memory. */
        public static function unpackFrom(context:as3flatbuffers.UnpackContext, base:uint, destination:Item):Item
        {
            const vtable:uint = as3flatbuffers.Unpack.vtable(context, base);
            const vtableSize:uint = li16(vtable);
            const objectSize:uint = li16(vtable + 2);
            if (!destination)
                destination = new Item();

            const position0:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 4, 4);
            if (!position0)
            {
                destination.id = 0;
            }
            else
            {
                destination.id = uint(li32(position0));
            }

            const position1:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 6, 4);
            if (!position1)
            {
                destination.quantity = 1;
            }
            else
            {
                destination.quantity = uint(li32(position1));
            }

            const position2:uint = as3flatbuffers.Unpack.fieldOffset(vtable, vtableSize, objectSize, base, 8, 1);
            if (!position2)
            {
                destination.rarity = 0;
            }
            else
            {
                destination.rarity = li8(position2);
            }
            return destination;
        }

        /** Replace dst with packed bytes. Writes little-endian without changing dst.endian. Returns dst at position zero. */
        public static function packSizePrefixed(source:Item, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.PackContext = PACK;
            try
            {
                as3flatbuffers.Pack.beginRoot(context, dst, true, false, 0);
                const root:uint = packInto(source, context);
                as3flatbuffers.Pack.finishRoot(context, root, true);
            }
            finally
            {
                as3flatbuffers.Pack.reset(context);
            }
            return dst;
        }

        /** Decode one size-prefixed frame at offset; references are bounded to its declared length. */
        public static function unpackSizePrefixed(bytes:flash.utils.ByteArray, destination:Item = null, offset:uint = 0):Item
        {
            const context:as3flatbuffers.UnpackContext = UNPACK;
            const previous:flash.utils.ByteArray = as3flatbuffers.Unpack.beginSizePrefixed(context, bytes, offset);
            try
            {
                destination = unpackFrom(context, as3flatbuffers.Unpack.root(context, 4), destination);
            }
            finally
            {
                as3flatbuffers.Unpack.end(context, previous);
            }
            return destination;
        }
    }
}
