// Code generated by as3flatc. DO NOT EDIT.
package example.inventory
{
    import as3flatbuffers.Pack;
    import as3flatbuffers.Unpack;
    import as3flatbuffers.UnpackContext;
    import avm2.intrinsics.memory.*;
    import flash.utils.ByteArray;

    /** Owned inline struct. pack() writes raw struct bytes into the destination. */
    public final class Position
    {
        private static const PACK:as3flatbuffers.PackContext = new as3flatbuffers.PackContext();
        private static const UNPACK:as3flatbuffers.UnpackContext = new as3flatbuffers.UnpackContext();

        public var x:Number = 0;
        public var y:Number = 0;

        public static function reset(msg:Position):void
        {
            msg.x = 0;
            msg.y = 0;
        }

        public static function clone(source:Position):Position
        {
            if (!source)
                return null;

            const destination:Position = new Position();
            destination.x = source.x;
            destination.y = source.y;

            return destination;
        }

        /** Replace dst with packed bytes. Caller must select little-endian. Returns dst at position zero. */
        public static function pack(source:Position, dst:flash.utils.ByteArray):flash.utils.ByteArray
        {
            if (!source || !dst)
                throw new ArgumentError("Source and destination must be non-null");

            const context:as3flatbuffers.PackContext = PACK;
            try
            {
                as3flatbuffers.Pack.begin(context, dst, false);
                as3flatbuffers.Pack.finish(context, packInto(source, context));
            }
            finally
            {
                as3flatbuffers.Pack.reset(context);
            }
            return dst;
        }

        /** Write into an active context and return the absolute object offset. */
        public static function packInto(source:Position, context:as3flatbuffers.PackContext):uint
        {
            if (!source || !context)
                throw new ArgumentError("Source and context must be non-null");

            const bytes:flash.utils.ByteArray = as3flatbuffers.Pack.prepareStruct(context, 8, 4);
            const start:uint = bytes.position;

            bytes.writeFloat(source.x);
            bytes.writeFloat(source.y);
            return start;
        }

        /** Decode raw struct bytes at offset into a new or reused owned value. */
        public static function unpack(bytes:flash.utils.ByteArray, destination:Position = null, offset:uint = 0):Position
        {
            const context:as3flatbuffers.UnpackContext = UNPACK;
            const previous:flash.utils.ByteArray = as3flatbuffers.Unpack.begin(context, bytes);
            try
            {
                destination = unpackFrom(context, offset, destination);
            }
            finally
            {
                as3flatbuffers.Unpack.end(context, previous);
            }
            return destination;
        }

        /** Internal generated entry point; context must already own domain memory. */
        public static function unpackFrom(context:as3flatbuffers.UnpackContext, base:uint, destination:Position):Position
        {
            as3flatbuffers.Unpack.struct(context, base, 8);
            if (!destination)
                destination = new Position();

            destination.x = lf32(base + 0);

            destination.y = lf32(base + 4);
            return destination;
        }
    }
}
