// Code generated by as3flatc. DO NOT EDIT.
package example.inventory
{
    /** Named enum values. Fields use the underlying integer type and preserve unknown values. */
    public final class Rarity
    {
        public static const COMMON:uint = 0;
        public static const RARE:uint = 1;
        public static const EPIC:uint = 2;
    }
}
