package internal

import (
	"bytes"
	"path"
	"sort"
	"strings"
)

func generateFiles(objects []object) ([]File, error) {
	byName := make(map[string]object, len(objects))
	for _, o := range objects {
		byName[objectType(o)] = o
	}
	emitMessage := func(w *IndentWriter, o object) { generateMessage(w, o, byName) }
	var files []File
	for _, o := range objects {
		specs := []struct {
			suffix string
			emit   func(*IndentWriter, object)
		}{{"", emitMessage}, {"View", generateView}}
		if o.Union != nil {
			specs[0].emit = generateUnion
			specs[1].emit = generateUnionView
		} else if o.Enum != nil {
			specs = specs[:1]
			specs[0].emit = generateEnum
		}
		for _, spec := range specs {
			var output bytes.Buffer
			writer := NewIndentWriter(&output, DefaultIndent)
			spec.emit(&writer, o)
			if e := writer.Err(); e != nil {
				return nil, e
			}
			files = append(files, File{
				Name: path.Join(strings.ReplaceAll(o.Package, ".", "/"), o.Name+spec.suffix+".as"),
				Data: output.Bytes(),
			})
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Name < files[j].Name })
	return files, nil
}

func generatePackage(w *IndentWriter, o object) {
	w.Line("// Code generated by as3flatc. DO NOT EDIT.")
	if o.Package == "" {
		w.Line("package")
	} else {
		w.Line("package %s", o.Package)
	}
	w.Line("{")
	w.Indent()
}

func endPackage(w *IndentWriter) {
	w.Dedent()
	w.Line("}")
}
