package internal

func generateUnionView(w *IndentWriter, o object) {
	generatePackage(w, o)
	w.Line("import flash.utils.ByteArray;")
	w.Line("import flash.utils.Endian;")
	generateStructImports(w, object{Fields: o.Union.Members}, true)
	w.BlankLine()
	w.Line("/** Borrowed tagged union. Only the selected member getter returns a value. */")
	w.Line("public final class %sView", o.Name)
	w.Line("{")
	w.Indent()
	w.Line("private var bytes:ByteArray;")
	w.Line("private var tag:uint;")
	w.Line("private var position:uint;")
	for _, f := range o.Union.Members {
		if !f.String {
			w.Line("private var %s:%sView;", f.ViewCache, f.Type)
		}
	}
	w.BlankLine()
	generateUnionBind(w, o)
	w.BlankLine()
	w.Line("public function get type():uint")
	w.Line("{")
	w.Indent()
	w.Line("return tag;")
	w.Dedent()
	w.Line("}")
	for _, f := range o.Union.Members {
		w.BlankLine()
		typ := f.Type
		if !f.String {
			typ += "View"
		}
		w.Line("public function get %s():%s", f.Name, typ)
		w.Line("{")
		w.Indent()
		w.Line("if (tag != %s.%s)", o.Name, f.Symbol)
		w.Indent()
		w.Line("return null;")
		w.Dedent()
		if f.String {
			w.Line("bytes.position = position;")
			w.Line("const length:uint = bytes.readUnsignedInt();")
			w.Line("const start:uint = bytes.position;")
			w.Line("if (length >= bytes.length - start)")
			w.Indent()
			w.Line("throw new RangeError(\"Truncated union string\");")
			w.Dedent()
			w.Line("if (bytes[start + length] != 0)")
			w.Indent()
			w.Line("throw new RangeError(\"String terminator must be zero\");")
			w.Dedent()
			w.Line("return bytes.readUTFBytes(length);")
		} else {
			generateLazyTableView(w, f, "this")
			w.Line("this.%s.bind(bytes, position);", f.ViewCache)
			w.Line("return this.%s;", f.ViewCache)
		}
		w.Dedent()
		w.Line("}")
	}
	w.Dedent()
	w.Line("}")
	endPackage(w)
}

func generateUnionBind(w *IndentWriter, o object) {
	w.Line("/** Bind a tag and the absolute position of its payload-offset word (zero if absent). */")
	w.Line("public function bind(input:ByteArray, type:uint, reference:uint):%sView", o.Name)
	w.Line("{")
	w.Indent()
	w.Line("bytes = null;")
	w.Line("tag = 0;")
	w.Line("position = 0;")
	w.Line("if (!input)")
	w.Indent()
	w.Line("throw new ArgumentError(\"Input must be non-null\");")
	w.Dedent()
	w.Line("input.endian = Endian.LITTLE_ENDIAN;")
	w.Line("var width:uint = 0;")
	w.Line("switch (type)")
	w.Line("{")
	w.Indent()
	w.Line("case %s.NONE:", o.Name)
	w.Indent()
	w.Line("break;")
	w.Dedent()
	for _, f := range o.Union.Members {
		w.Line("case %s.%s:", o.Name, f.Symbol)
		w.Indent()
		w.Line("width = %d;", f.Width)
		w.Line("break;")
		w.Dedent()
	}
	w.Line("default:")
	w.Indent()
	w.Line("throw new RangeError(\"Unknown union tag\");")
	w.Dedent()
	w.Dedent()
	w.Line("}")
	w.Line("var relative:uint = 0;")
	w.Line("if (reference)")
	w.Line("{")
	w.Indent()
	w.Line("if (Number(reference) + 4 > input.length)")
	w.Indent()
	w.Line("throw new RangeError(\"Truncated union reference\");")
	w.Dedent()
	w.Line("input.position = reference;")
	w.Line("relative = input.readUnsignedInt();")
	w.Dedent()
	w.Line("}")
	w.Line("if (type == %s.NONE)", o.Name)
	w.Line("{")
	w.Indent()
	w.Line("if (relative)")
	w.Indent()
	w.Line("throw new RangeError(\"NONE union has a payload\");")
	w.Dedent()
	w.Dedent()
	w.Line("}")
	w.Line("else")
	w.Line("{")
	w.Indent()
	w.Line("if (!reference || relative < 4 || Number(reference) + relative + width > input.length)")
	w.Indent()
	w.Line("throw new RangeError(\"Invalid union payload offset\");")
	w.Dedent()
	w.Line("position = reference + relative;")
	w.Dedent()
	w.Line("}")
	w.Line("tag = type;")
	w.Line("bytes = input;")
	w.Line("return this;")
	w.Dedent()
	w.Line("}")
}
