package internal

func generateBoundCheck(w *IndentWriter) {
	w.Line("if (!bytes)")
	w.Indent()
	w.Line("throw new Error(\"View is not bound\");")
	w.Dedent()
}

func generateTableBind(w *IndentWriter, o object) {
	w.Line("/** Bind directly to a table's absolute byte position. */")
	w.Line("public function bind(input:flash.utils.ByteArray, offset:uint):%sView", o.Name)
	w.Line("{")
	w.Indent()
	w.Line("bytes = null;")
	w.Line("if (!input)")
	w.Indent()
	w.Line("throw new ArgumentError(\"Input must be non-null\");")
	w.Dedent()
	w.Line("if (offset > input.length || input.length - offset < 4)")
	w.Indent()
	w.Line("throw new RangeError(\"Truncated table\");")
	w.Dedent()
	w.BlankLine()
	w.Line("input.endian = Endian.LITTLE_ENDIAN;")
	w.Line("input.position = offset;")
	w.Line("const voffset:Number = Number(offset) - input.readInt();")
	w.Line("if (voffset < 0 || voffset > input.length - 4)")
	w.Indent()
	w.Line("throw new RangeError(\"Invalid vtable offset\");")
	w.Dedent()
	w.BlankLine()
	w.Line("input.position = uint(voffset);")
	w.Line("const vtSize:uint = input.readUnsignedShort();")
	w.Line("const objSize:uint = input.readUnsignedShort();")
	w.Line("if (vtSize < 4 || (vtSize & 1) || vtSize > input.length - voffset ||")
	w.Line("        objSize < 4 || objSize > input.length - offset)")
	w.Indent()
	w.Line("throw new RangeError(\"Invalid table size\");")
	w.Dedent()
	w.BlankLine()
	w.Line("table = offset;")
	w.Line("vtable = uint(voffset);")
	w.Line("vtableSize = vtSize;")
	w.Line("objectSize = objSize;")
	w.Line("bytes = input;")
	w.Line("return this;")
	w.Dedent()
	w.Line("}")
}

func generateFieldOffset(w *IndentWriter) {
	w.Line("[Inline]")
	w.Line("private final function fieldOffset(slot:uint, width:uint):uint")
	w.Line("{")
	w.Indent()
	generateBoundCheck(w)
	w.Line("if (slot >= vtableSize)")
	w.Indent()
	w.Line("return 0;")
	w.Dedent()
	w.BlankLine()
	w.Line("bytes.position = vtable + slot;")
	w.Line("const relative:uint = bytes.readUnsignedShort();")
	w.Line("if (!relative)")
	w.Indent()
	w.Line("return 0;")
	w.Dedent()
	w.Line("if (relative < 4 || relative > objectSize || width > objectSize - relative)")
	w.Indent()
	w.Line("throw new RangeError(\"Field lies outside its table\");")
	w.Dedent()
	w.BlankLine()
	w.Line("return table + relative;")
	w.Dedent()
	w.Line("}")
}

func generateStructBind(w *IndentWriter, o object) {
	w.Line("public function bind(input:flash.utils.ByteArray, offset:uint):%sView", o.Name)
	w.Line("{")
	w.Indent()
	w.Line("bytes = null;")
	w.Line("if (!input)")
	w.Indent()
	w.Line("throw new ArgumentError(\"Input must be non-null\");")
	w.Dedent()
	w.Line("if (offset > input.length || %d > input.length - offset)", o.Size)
	w.Indent()
	w.Line("throw new RangeError(\"Truncated struct\");")
	w.Dedent()
	w.BlankLine()
	w.Line("input.endian = Endian.LITTLE_ENDIAN;")
	w.Line("base = offset;")
	w.Line("bytes = input;")
	w.Line("return this;")
	w.Dedent()
	w.Line("}")
}
