package internal

func generateUnionVectorView(w *IndentWriter, f field) {
	e := *f.Element
	w.Line("public function get %s():uint", f.LengthName)
	w.Line("{")
	w.Indent()
	generateUnionVectorViewPositions(w, f)
	w.Line("return count;")
	w.Dedent()
	w.Line("}")
	w.BlankLine()
	w.Line("/** Returns a cached union view rebound on each access. */")
	w.Line("public function %s(index:uint):%sView", f.Name, e.Type)
	w.Line("{")
	w.Indent()
	generateUnionVectorViewPositions(w, f)
	w.Line("if (index >= count)")
	w.Indent()
	w.Line("throw new RangeError(\"Union vector index is out of range\");")
	w.Dedent()
	e.ViewCache = f.ViewCache
	generateLazyTableView(w, e, "this")
	w.Line("bytes.position = tags + 4 + index;")
	w.Line("const tag:uint = bytes.readUnsignedByte();")
	w.Line("return this.%s.bind(bytes, tag, vector + 4 + index * 4);", f.ViewCache)
	w.Dedent()
	w.Line("}")
}

func generateUnionVectorViewPositions(w *IndentWriter, f field) {
	w.Line("const tags:uint = vectorOffset(%d, 1);", 4+uint32(f.ID-1)*2)
	w.Line("const vector:uint = vectorOffset(%d, 4);", 4+uint32(f.ID)*2)
	w.Line("var tagCount:uint = 0;")
	w.Line("var count:uint = 0;")
	w.Line("if (tags)")
	w.Line("{")
	w.Indent()
	w.Line("bytes.position = tags;")
	w.Line("tagCount = bytes.readUnsignedInt();")
	w.Dedent()
	w.Line("}")
	w.Line("if (vector)")
	w.Line("{")
	w.Indent()
	w.Line("bytes.position = vector;")
	w.Line("count = bytes.readUnsignedInt();")
	w.Dedent()
	w.Line("}")
	w.Line("if ((tags == 0) != (vector == 0) || tagCount != count)")
	w.Indent()
	w.Line("throw new RangeError(\"Union tag and payload vectors must match\");")
	w.Dedent()
}
