package internal

import (
	"bytes"
	"path"
	"sort"
	"strings"
)

func generateFiles(objects []object) ([]File, error) {
	var files []File
	for _, o := range objects {
		for _, spec := range []struct {
			suffix string
			emit   func(*IndentWriter, object)
		}{{"", generateMessage}, {"View", generateView}} {
			var output bytes.Buffer
			writer := NewIndentWriter(&output, DefaultIndent)
			spec.emit(&writer, o)
			if e := writer.Err(); e != nil {
				return nil, e
			}
			files = append(files, File{
				Name: path.Join(strings.ReplaceAll(o.Package, ".", "/"), o.Name+spec.suffix+".as"),
				Data: output.Bytes(),
			})
		}
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Name < files[j].Name })
	return files, nil
}

func generatePackage(w *IndentWriter, o object) {
	w.Line("// Code generated by as3flatc. DO NOT EDIT.")
	if o.Package == "" {
		w.Line("package")
	} else {
		w.Line("package %s", o.Package)
	}
	w.Line("{")
	w.Indent()
}

func endPackage(w *IndentWriter) {
	w.Dedent()
	w.Line("}")
}
