package internal

import (
	"regexp"
)

var identifier = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

var as3ReservedWords = map[string]struct{}{
	"AS3":          {},
	"as":           {},
	"break":        {},
	"case":         {},
	"catch":        {},
	"class":        {},
	"const":        {},
	"continue":     {},
	"default":      {},
	"delete":       {},
	"do":           {},
	"dynamic":      {},
	"else":         {},
	"extends":      {},
	"false":        {},
	"final":        {},
	"finally":      {},
	"flash_proxy":  {},
	"for":          {},
	"function":     {},
	"get":          {},
	"if":           {},
	"implements":   {},
	"import":       {},
	"in":           {},
	"include":      {},
	"instanceof":   {},
	"interface":    {},
	"internal":     {},
	"is":           {},
	"label":        {},
	"namespace":    {},
	"native":       {},
	"new":          {},
	"null":         {},
	"object_proxy": {},
	"override":     {},
	"package":      {},
	"private":      {},
	"protected":    {},
	"public":       {},
	"return":       {},
	"set":          {},
	"static":       {},
	"super":        {},
	"switch":       {},
	"this":         {},
	"throw":        {},
	"true":         {},
	"try":          {},
	"typeof":       {},
	"use":          {},
	"var":          {},
	"void":         {},
	"while":        {},
	"with":         {},
}

// IsAS3ReservedWord reports whether word is reserved in ActionScript 3.
func IsAS3ReservedWord(word string) bool {
	_, ok := as3ReservedWords[word]
	_, additional := additionalReserved[word]
	return ok || additional
}

var typeNames = map[string]struct{}{
	"PACK":            {},
	"Endian":          {},
	"StructView":      {},
	"OptionalInt":     {},
	"OptionalUint":    {},
	"OptionalNumber":  {},
	"OptionalBoolean": {},

	"Int64":         {},
	"UInt64":        {},
	"Array":         {},
	"Boolean":       {},
	"UnpackContext": {},
	"UNPACK":        {},
	"PackContext":   {},
	"Unpack":        {},
	"Pack":          {},
	"ByteArray":     {},
	"Date":          {},
	"Error":         {},
	"Function":      {},
	"Infinity":      {},
	"NaN":           {},
	"Namespace":     {},
	"Number":        {},
	"Object":        {},
	"QName":         {},
	"RegExp":        {},
	"String":        {},
	"TableView":     {},
	"Vector":        {},
	"XML":           {},
	"XMLList":       {},
	"int":           {},
	"uint":          {},
	"undefined":     {},
}

var additionalReserved = map[string]struct{}{
	"abstract":     {},
	"boolean":      {},
	"byte":         {},
	"cast":         {},
	"char":         {},
	"debugger":     {},
	"double":       {},
	"each":         {},
	"enum":         {},
	"export":       {},
	"float":        {},
	"goto":         {},
	"intrinsic":    {},
	"long":         {},
	"prototype":    {},
	"short":        {},
	"synchronized": {},
	"throws":       {},
	"to":           {},
	"transient":    {},
	"type":         {},
	"virtual":      {},
	"volatile":     {},
}
